### PR TITLE
Use cascade layers for Open Props

### PR DESCRIPTION
**Pull request by argyleink**
i like cascade layers, great for portioning off styles, like a reset or normalize. this is a much more optional tweak to the usage, just a habit i've been liking getting into.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Just for my own sanity. If a browser doesn't support cascade layers the syntax in this page would still "just work"

**Comment by argyleink** [comment]
it won't, the browser would silently fail to import. the whole rule is invalidated since it doesnt understand the entirety

**Comment by PaulKinlan** [comment]
I don't know if we should include this... If a developer/user visits this site in Safari (not TP) then it won't work.... right?

It might be useful to wrap it in a `@supports at-rule(@layer) {`

**Comment by argyleink** [comment]
It's in Safari stable 👍🏻 

The way I import and insert into a layer at the same time can't go in @supports, has to be top of file. 

if you're worried about it but curious or want to have it be an option, we could comment out the @layer import code in the css file, so anyone that inspects it could see an alt way of managing it?

Using cascade layers like this is very meaningful to authors, but i get it if you've got cold feat cuz it feels new

**Comment by PaulKinlan** [comment]
Thanks for educating me. Appreciate it.

**Pull request merged**
